CREATE DATABASE IF NOT EXISTS assignmentdb;
USE assignmentdb;

DROP TABLE IF EXISTS Student;

CREATE TABLE Student (
    info090 INT NOT NULL PRIMARY KEY,
    info090name VARCHAR(20),
    HOD VARCHAR(20)
);

DESC Student;
SHOW TABLES;
